data:
  train_path: 'data/labeled_data.csv'
  test_path: 'data/labeled_data_test.csv'
  test_size: 0.2
  random_state: 42

models:
  - name: 'bert-base-uncased'
    type: 'bert'
  - name: 'roberta-base'
    type: 'roberta'
  - name: 'distilbert-base-uncased'
    type: 'distilbert'

training:
  max_length: 128
  num_labels: 3
  num_train_epochs: 4
  per_device_train_batch_size: 256
  logging_steps: 10
  eval_strategy: 'steps'
  save_strategy: 'epoch'

evaluation:
  batch_size: 256